export {
  DOCX_PAGE_SIZE,
  FLOWCHART_NODE_SPACING,
  FLOWCHART_RANK_SPACING,
  FLOWCHART_WRAPPING_WIDTH,
  HIDDEN_CODE_BLOCK_LANGUAGES,
  IMAGE_EXTENSIONS,
  MERMAID_RENDER_SCALE,
  TWIPS_PER_PIXEL,
} from '@markdocx/core';
